### ISSUE TITLE
where to get GUIX profile and Mispriming

### ISSUE THREAD

**Issue by N-damo** [SdeBlank/NanoFG#17]
Dear developer:
 I downloaded primer3 software, I found primer3-core, but not GUIX profile and Mispriming in its source directory. I guess the two file may place in the other place, could you give me some help to locate them?
Thanks
best regards
LianLin

**Comment by SdeBlank** [comment]
Hi,

These files are indeed not default in a clean primer3 installation. This is a remnant of files that I had access to before which is why I have not spotted this issue before.

I will try to rework the primer design code to be applicable with the base primer3 software when i have the time. 
Until then, you can still run NanoFG and do primer design manually on the output fusion sequences.

Cheers,
Sam

**Comment by SdeBlank** [comment]
Hi again,

I think i managed to rewrite the primer design. NanoFG should now work with a base installation of primer3. GUIX-profile and mispriming are not required anymore.

Cheers,
Sam

**Comment by N-damo** [comment]
Thanks for the quick reply. 
LianLin
